name: deployer-test
on:
    pull_request: null
    push:
        branches:
            - master
    schedule:
        -
            cron: '* 2 * * 2'
jobs:
    prerelease:
        runs-on: ubuntu-latest
        name: prerelease deployer end-to-end test
        steps:
            -
                name: prerelease
                id: prerelease
                uses: mshanemc/deployer-check-javascript-action@master
                with:
                    deployer-url: 'https://deployer-prerelease.herokuapp.com'
